%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\melkiga\Google Drive\Research\Cano\MultiInstanceClassification\WekaTesting\output\ResultsTime.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/03/23 17:32:12

%% Import the data
[~, ~, raw] = xlsread('C:\Users\melkiga\Google Drive\Research\Cano\MultiInstanceClassification\WekaTesting\output\ResultsTime.xlsx','Sheet1','A2:C150');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2]);
raw = raw(:,3);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Algorithm = cellVectors(:,1);
DataSet = cellVectors(:,2);
Time = data(:,1);

%% Clear temporary variables
clearvars data raw cellVectors;