#!/bin/sh
java -cp MIexperiments.jar mi.experimental.BaggingTLCTest component eastWest elephant fox function musk1 musk2 mutagenesis-atoms mutagenesis-bonds mutagenesis-chains suramin tiger trx webmining westEast &
java -cp MIexperiments.jar mi.experimental.MIBoostTest component eastWest elephant fox function musk1 musk2 mutagenesis-atoms mutagenesis-bonds mutagenesis-chains suramin tiger trx webmining westEast &
java -cp MIexperiments.jar mi.experimental.MIDDTest component eastWest elephant fox function musk1 musk2 mutagenesis-atoms mutagenesis-bonds mutagenesis-chains suramin tiger trx webmining westEast &
java -cp MIexperiments.jar mi.experimental.MINNDTest component eastWest elephant fox function musk1 musk2 mutagenesis-atoms mutagenesis-bonds mutagenesis-chains suramin tiger trx webmining westEast &
java -cp MIexperiments.jar mi.experimental.MIOptimalBallTest component eastWest elephant fox function musk1 musk2 mutagenesis-atoms mutagenesis-bonds mutagenesis-chains suramin tiger trx webmining westEast &
java -cp MIexperiments.jar mi.experimental.MISMOTest component eastWest elephant fox function musk1 musk2 mutagenesis-atoms mutagenesis-bonds mutagenesis-chains suramin tiger trx webmining westEast &
java -cp MIexperiments.jar mi.experimental.MISVMTest component eastWest elephant fox function musk1 musk2 mutagenesis-atoms mutagenesis-bonds mutagenesis-chains suramin tiger trx webmining westEast &
java -cp MIexperiments.jar mi.experimental.MIWrapperTest component eastWest elephant fox function musk1 musk2 mutagenesis-atoms mutagenesis-bonds mutagenesis-chains suramin tiger trx webmining westEast &
java -cp MIexperiments.jar mi.experimental.SMITest component eastWest elephant fox function musk1 musk2 mutagenesis-atoms mutagenesis-bonds mutagenesis-chains suramin tiger trx webmining westEast &
java -cp MIexperiments.jar mi.experimental.StackingTest component eastWest elephant fox function musk1 musk2 mutagenesis-atoms mutagenesis-bonds mutagenesis-chains suramin tiger trx webmining westEast &
java -cp MIexperiments.jar mi.experimental.TLCTest component eastWest elephant fox function musk1 musk2 mutagenesis-atoms mutagenesis-bonds mutagenesis-chains suramin tiger trx webmining westEast &